# Generated by Django 3.1.6 on 2021-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210416_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrients_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
