# Generated by Django 3.1.6 on 2021-10-13 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_nutrients_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='category',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='code',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='nutriscore',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='url',
        ),
    ]
