# Generated by Django 3.1.6 on 2021-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('picture', models.URLField()),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.Category')),
            ],
        ),
    ]
