# Generated by Django 3.1.6 on 2021-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='code',
            field=models.CharField(default='abcdefg', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='abcdefg', max_length=64),
            preserve_default=False,
        ),
    ]
