# Generated by Django 3.1.6 on 2021-03-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
