# Generated by Django 3.1.6 on 2021-03-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_favorite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
