# Generated by Django 3.1.6 on 2021-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
