# Generated by Django 3.1.6 on 2021-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210322_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
